# Generated by Django 5.0.3 on 2024-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='completion_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='year_released',
            field=models.IntegerField(),
        ),
    ]
