# Generated by Django 5.0.3 on 2024-03-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_alter_game_completion_time_alter_game_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='min_age',
            field=models.IntegerField(),
        ),
    ]
